# Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

# 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

# It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

# Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?

pentagons = []
distances = []

for n in range(1, 5000):
	pentagons.append(int(n*(3*n-1)/2))

for p1 in pentagons:
	for p2 in pentagons:
		if p2 < p1:
			pentSum = p1 + p2
			pentDif = p1 - p2
			if pentSum in pentagons and pentDif in pentagons:
				distances.append(pentDif)

	if len(distances) > 0:
		break
	
print(distances)

